#+TITLE: evil-org

[[https://melpa.org/#/evil-org][file:https://melpa.org/packages/evil-org-badge.svg]]
[[https://stable.melpa.org/#/evil-org][file:https://stable.melpa.org/packages/evil-org-badge.svg]]

Supplemental evil-mode key-bindings to Emacs org-mode.
This project is a continuation of
https://github.com/edwtjo/evil-org-mode/blob/master/evil-org.el by Edward Tjörnhammar.
From version 1.3 it was taken over by Somelauw.
See [[file:doc/changelog.org][changelog]] for a history of changes.

** Features
 - normal, visual and insert mode bindings
 - key bindings organised in key themes
 - operators like > and < to work on headings
 - text objects
 - table support

** Keybindings

   |----------------+---------------------------|
   | key            | explanation               |
   |----------------+---------------------------|
   | M-ret          | insert heading            |
   | TAB            | fold / unfold headings    |
   | gh, gj, gk, gl | navigate between elements |
   | vae            | select an element         |
   | var            | select a subtree          |
   | M-h or <<      | promote a heading         |
   | M-l or >>      | demote a heading          |
   | M-k            | move subtree up           |
   | M-j            | move subtree down         |
   | M-S-h or <ar   | promote a subtree         |
   | M-S-l or >ar   | demote a subtree          |
   |----------------+---------------------------|

   [[file:doc/keythemes.org][Full overview of bindings and configuration]]

** Requirements

   - org-mode, git://orgmode.org/org-mode.git
   - evil-mode, https://bitbucket.org/lyro/evil

** Installation

*** Manual installation
    #+BEGIN_SRC sh
    mkdir -p ~/.emacs.d/plugins; git clone
    git://github.com/somelauw/evil-org.git ~/.emacs.d/plugins/evil-org
    #+END_SRC

**** Configuration emacs.el

    #+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "~/.emacs.d/plugins/evil-org")
    (require 'evil-org)
    (add-hook 'org-mode-hook 'evil-org-mode)
    (evil-org-set-key-theme '(navigation insert textobjects additional))
    #+END_SRC

    Or you can customize =evil-org-key-theme= and replace the last line by:
    #+BEGIN_SRC emacs-lisp
    (evil-org-set-key-theme)
    #+END_SRC

*** Installation by use-package
    #+BEGIN_SRC emacs-lisp
    (use-package evil-org
      :ensure t
      :after org
      :config
      (add-hook 'org-mode-hook 'evil-org-mode)
      (add-hook 'evil-org-mode-hook
                (lambda ()
                  (evil-org-set-key-theme))))
    #+END_SRC

For a more elaborate setup, take a look at [[file:doc/example_config.el][this example]].

** See also

   - [[https://github.com/edwtjo/evil-org-mode][evil-org-mode by edwtjo]]
     Original org-mode plugin by edwtjo from which this project was forked

   - [[https://github.com/GuiltyDolphin/org-evil][org-evil by GuiltyDolphin]]
     Alternative integration of evil and org with different keybindings

   - https://github.com/jceb/vim-orgmode
     Org mode plugin for vim

   - http://orgmode.org/
     The official org-mode website

   - [[http://orgmode.org/orgcard.pdf]]
     A handy cheat sheet, even if using this plugin

   - https://github.com/Somelauw/evil-markdown
     Similar project for markdown code

** License

 Gnu General Public License v3.0, http://www.gnu.org/copyleft/gpl.html
